"""You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

Runtime - 0ms: Beats 100%
Memory - 12.33mb: Beats 86.98%
"""

s = "acds"
t = "abcdsa"
def findTheDifference(self, s, t):
    for i in t:
        if i not in s:
            return i
        elif t.count(i) > s.count(i):
            return i
